Food Expenses: food-icon.png
Travel: travel-icon.png 
Rent or Mortgage: home-icon.png
Utilities: utilities-icon.png
Groceries: groceries-icon.png
Dining Out: dining-icon.png
Transportation: transport-icon.png
Insurance: insurance-icon.png
Health and Wellness: health-icon.png
Entertainment: entertainment-icon.png
Shopping: shopping-icon.png
Clothing: clothing-icon.png
Education: education-icon.png
Childcare: childcare-icon.png
Savings: savings-icon.png
Investments: investments-icon.png
Debt Repayment: debt-icon.png
Travel: travel-icon.png
Gifts and Donations: gifts-icon.png
Taxes: taxes-icon.png
Home Maintenance: maintenance-icon.png
Personal Care: personal-care-icon.png
Pet Expenses: pet-icon.png
Electronics and Gadgets: electronics-icon.png
Hobbies and Leisure: hobbies-icon.png
Miscellaneous: miscellaneous-icon.png
